# Generated by Django 4.2.7 on 2023-11-25 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_rename_type_rate_currency_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='currency_type',
            new_name='type',
        ),
    ]
