# Generated by Django 4.2.7 on 2023-11-28 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
