# Generated by Django 4.2.7 on 2023-11-28 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_source_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='created',
        ),
        migrations.AddField(
            model_name='source',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
    ]
