# Generated by Django 4.2.7 on 2023-11-28 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0008_remove_source_created_source_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='created',
        ),
    ]
