# Generated by Django 4.2.7 on 2023-11-28 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0010_rate_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='type',
        ),
    ]
